"use client";
import { useMemo, useState } from "react";
import { ExternalLink, KeyRound, MoreHorizontal, Plus, Search } from "lucide-react";
import PageHeader from "@/components/PageHeader"; import DataState from "@/components/DataState"; import ConfirmDialog from "@/components/ConfirmDialog";
import { useCan } from "@/components/RoleProvider"; import { Badge } from "@/components/ui/badge"; import { Button } from "@/components/ui/button"; import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { DropdownMenu, DropdownMenuContent, DropdownMenuItem, DropdownMenuTrigger } from "@/components/ui/dropdown-menu"; import { Input } from "@/components/ui/input"; import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { useList } from "@/hooks/use-list"; import { useDebounced } from "@/hooks/use-debounced"; import { useProjectOptions } from "@/hooks/use-options"; import { api, mutate } from "@/lib/api-client";
import { PARTNER_STATUS, PARTNER_STATUS_LABEL, PARTNER_STATUS_VARIANT } from "@/lib/enums"; import { fmtMoneyShort } from "@/lib/format"; import SupplierDialog from "./supplier-dialog"; import type { Supplier } from "../desks/types";

export default function SuppliersPage() {
  const showCost = useCan()("cost"); const [q, setQ] = useState(""); const debouncedQ = useDebounced(q); const [projectId, setProjectId] = useState("all"); const [status, setStatus] = useState("all");
  const path = useMemo(() => `/api/suppliers?${new URLSearchParams({ q: debouncedQ, projectId, status })}`, [debouncedQ, projectId, status]); const { items, loading, error, reload } = useList<Supplier>(path); const projects = useProjectOptions();
  const [editing, setEditing] = useState<Supplier | null>(null); const [open, setOpen] = useState(false); const [deleting, setDeleting] = useState<Supplier | null>(null);
  return <><PageHeader title="供货方" subtitle="上游台子、接口地址与产品进货价" actions={<Button className="rounded-full" onClick={() => { setEditing(null); setOpen(true); }}><Plus size={14} />新增供货方</Button>} />
    <div className="flex flex-wrap gap-2 mb-4"><div className="relative"><Search size={14} className="absolute left-3 top-1/2 -translate-y-1/2 text-muted-foreground" /><Input className="pl-8 w-56" placeholder="搜索供货方名称" value={q} onChange={(e) => setQ(e.target.value)} /></div><Select value={projectId} onValueChange={setProjectId}><SelectTrigger className="w-44"><SelectValue /></SelectTrigger><SelectContent><SelectItem value="all">全部项目</SelectItem>{projects.map((p) => <SelectItem key={p.id} value={String(p.id)}>{p.name}</SelectItem>)}</SelectContent></Select><Select value={status} onValueChange={setStatus}><SelectTrigger className="w-32"><SelectValue /></SelectTrigger><SelectContent><SelectItem value="all">全部状态</SelectItem>{PARTNER_STATUS.map((s) => <SelectItem key={s} value={s}>{PARTNER_STATUS_LABEL[s]}</SelectItem>)}</SelectContent></Select></div>
    <DataState loading={loading} error={error} empty={!items.length} emptyText="还没有供货方" onRetry={reload}><div className="grid gap-3 md:grid-cols-2 xl:grid-cols-3">{items.map((s) => <Card key={s.id}><CardHeader className="pb-3"><div className="flex items-start gap-2"><div className="min-w-0 flex-1"><CardTitle className="text-base">{s.name}</CardTitle><p className="mt-1 text-xs text-muted-foreground">{s.project?.name ?? "-"}</p></div><Badge variant={PARTNER_STATUS_VARIANT[s.status]}>{PARTNER_STATUS_LABEL[s.status]}</Badge><DropdownMenu><DropdownMenuTrigger asChild><Button size="icon-sm" variant="ghost" aria-label="更多"><MoreHorizontal size={16} /></Button></DropdownMenuTrigger><DropdownMenuContent align="end"><DropdownMenuItem onSelect={() => { setEditing(s); setOpen(true); }}>编辑</DropdownMenuItem><DropdownMenuItem className="text-destructive" onSelect={() => setDeleting(s)}>删除</DropdownMenuItem></DropdownMenuContent></DropdownMenu></div></CardHeader><CardContent className="space-y-4">{s.baseUrl ? <a href={s.baseUrl} target="_blank" rel="noreferrer" className="flex items-center gap-2 truncate font-mono text-xs text-primary"><ExternalLink size={13} />{s.baseUrl}</a> : <p className="text-xs text-muted-foreground">未填写 Base URL</p>}<div className="border-t pt-3 space-y-3">{s.items.map((item) => <div key={item.id}><div className="flex justify-between gap-3 text-sm"><span>{item.productName || item.product.name}</span><span className="font-medium">{showCost && item.unitPrice !== null ? fmtMoneyShort(item.unitPrice) : "-"}</span></div>{item.apiKey && <p className="mt-1 flex items-center gap-1 truncate font-mono text-xs text-muted-foreground"><KeyRound size={12} />{item.apiKey}</p>}</div>)}{!s.items.length && <p className="text-xs text-muted-foreground">暂无产品信息</p>}</div></CardContent></Card>)}</div></DataState>
    <SupplierDialog open={open} onOpenChange={setOpen} initial={editing} onSaved={reload} /><ConfirmDialog open={deleting !== null} onOpenChange={(v) => !v && setDeleting(null)} title={`删除供货方「${deleting?.name ?? ""}」？`} description="删除后将进入回收站，可随时恢复。" onConfirm={async () => { if (!deleting) return; const ok = await mutate(() => api.del(`/api/suppliers/${deleting.id}`), { success: "已移至回收站", error: "删除失败" }); setDeleting(null); if (ok) reload(); }} />
  </>;
}
